import {
  int,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
  decimal,
  boolean,
  json,
  datetime,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extend this file with additional tables as your product grows.
 * Columns use camelCase to match both database fields and generated types.
 */
export const users = mysqlTable("users", {
  /**
   * Surrogate primary key. Auto-incremented numeric value managed by the database.
   * Use this for relations between tables.
   */
  id: int("id").autoincrement().primaryKey(),
  /** Manus OAuth identifier (openId) returned from the OAuth callback. Unique per user. */
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Conversations table — stores chat sessions with Jarvis
 */
export const conversations = mysqlTable("conversations", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).default("New Conversation"),
  context: text("context"), // JSON-stringified context for Jarvis memory
  isActive: boolean("isActive").default(true),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Conversation = typeof conversations.$inferSelect;
export type InsertConversation = typeof conversations.$inferInsert;

/**
 * Messages table — stores all chat messages between user and Jarvis
 */
export const messages = mysqlTable("messages", {
  id: int("id").autoincrement().primaryKey(),
  conversationId: int("conversationId").notNull(),
  userId: int("userId").notNull(),
  role: mysqlEnum("role", ["user", "assistant", "system"]).notNull(),
  content: text("content").notNull(),
  metadata: json("metadata"), // Stores tokens, model, etc.
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Message = typeof messages.$inferSelect;
export type InsertMessage = typeof messages.$inferInsert;

/**
 * Goals table — wealth-building goals and strategic objectives
 */
export const goals = mysqlTable("goals", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  category: mysqlEnum("category", [
    "income",
    "investment",
    "business",
    "skill",
    "network",
    "debt",
    "savings",
    "passive_income",
    "zakat",
    "other",
  ]).default("other"),
  status: mysqlEnum("status", ["pending", "in_progress", "completed", "paused"]).default(
    "pending"
  ),
  priority: mysqlEnum("priority", ["low", "medium", "high", "critical"]).default("medium"),
  targetValue: decimal("targetValue", { precision: 20, scale: 2 }),
  currentValue: decimal("currentValue", { precision: 20, scale: 2 }).default("0"),
  dueDate: datetime("dueDate"),
  assignedTo: varchar("assignedTo", { length: 255 }), // Board member, C-Suite, Manager, Worker
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Goal = typeof goals.$inferSelect;
export type InsertGoal = typeof goals.$inferInsert;

/**
 * Tasks table — actionable items assigned by Jarvis
 */
export const tasks = mysqlTable("tasks", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  goalId: int("goalId"),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  status: mysqlEnum("status", ["pending", "in_progress", "completed", "blocked"]).default(
    "pending"
  ),
  priority: mysqlEnum("priority", ["low", "medium", "high", "critical"]).default("medium"),
  assignedTo: varchar("assignedTo", { length: 255 }), // Org hierarchy role
  dueDate: datetime("dueDate"),
  estimatedHours: int("estimatedHours"),
  completedAt: timestamp("completedAt"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Task = typeof tasks.$inferSelect;
export type InsertTask = typeof tasks.$inferInsert;

/**
 * Briefings table — daily briefings generated by Jarvis
 */
export const briefings = mysqlTable("briefings", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  content: text("content").notNull(), // Full briefing markdown
  worldNews: text("worldNews"), // Current events context
  wealthUpdates: text("wealthUpdates"), // Strategy updates
  prioritizedTasks: json("prioritizedTasks"), // Array of top tasks
  motivationalInsight: text("motivationalInsight"),
  energyOptimization: text("energyOptimization"),
  sentViaEmail: boolean("sentViaEmail").default(false),
  sentViaTelegram: boolean("sentViaTelegram").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Briefing = typeof briefings.$inferSelect;
export type InsertBriefing = typeof briefings.$inferInsert;

/**
 * Wealth metrics table — KPI tracking for net worth, income, investments, etc.
 */
export const wealthMetrics = mysqlTable("wealthMetrics", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  metricType: mysqlEnum("metricType", [
    "net_worth",
    "monthly_income",
    "investment_portfolio",
    "business_revenue",
    "passive_income",
    "total_debt",
    "emergency_fund",
    "zakat_due",
  ]).notNull(),
  value: decimal("value", { precision: 20, scale: 2 }).notNull(),
  trend: mysqlEnum("trend", ["up", "down", "stable"]).default("stable"),
  percentageChange: decimal("percentageChange", { precision: 10, scale: 2 }).default("0"),
  recordedAt: timestamp("recordedAt").defaultNow().notNull(),
});

export type WealthMetric = typeof wealthMetrics.$inferSelect;
export type InsertWealthMetric = typeof wealthMetrics.$inferInsert;

/**
 * Org structure table — conglomerate hierarchy (Chairman → Board → C-Suite → Managers → Workers)
 */
export const orgStructure = mysqlTable("orgStructure", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  role: mysqlEnum("role", ["chairman", "board", "c_suite", "manager", "worker"]).notNull(),
  department: varchar("department", { length: 255 }), // e.g., "Investments", "Operations"
  responsibilities: text("responsibilities"),
  assignedGoals: json("assignedGoals"), // Array of goal IDs
  performance: decimal("performance", { precision: 5, scale: 2 }).default("0"), // 0-100 score
  notes: text("notes"),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type OrgStructure = typeof orgStructure.$inferSelect;
export type InsertOrgStructure = typeof orgStructure.$inferInsert;

/**
 * Insights table — AI-generated insights and recommendations
 */
export const insights = mysqlTable("insights", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  content: text("content").notNull(),
  category: mysqlEnum("category", [
    "strategy",
    "opportunity",
    "risk",
    "optimization",
    "islamic_finance",
    "other",
  ]).default("other"),
  actionItems: json("actionItems"), // Array of recommended actions
  isRead: boolean("isRead").default(false),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Insight = typeof insights.$inferSelect;
export type InsertInsight = typeof insights.$inferInsert;

/**
 * Agent state table — stores Jarvis agent configuration and learning state
 */
export const agentState = mysqlTable("agentState", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  systemPrompt: text("systemPrompt").notNull(), // Jarvis persona definition
  learningData: json("learningData"), // Self-optimization data
  preferences: json("preferences"), // User preferences for agent behavior
  lastOptimizationAt: timestamp("lastOptimizationAt"),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type AgentState = typeof agentState.$inferSelect;
export type InsertAgentState = typeof agentState.$inferInsert;